# Assignment VI: NumPy Practice
## Uzbek Version

NumPy bo‘yicha bilimingizni ushbu yangi topshiriqlar orqali sinab ko‘ring.
Bu notebook oldingisiga qaraganda biroz murakkabroq va qiziqarliroq.

### Ko‘rsatmalar
- Kodni bo‘sh code hujayralarga yozing
- Berilgan o‘zgaruvchilarni o‘chirmang
- Har bir topshiriqni imkon qadar NumPy funksiyalari bilan bajaring
- Kod yozishdan oldin topshiriqni diqqat bilan o‘qing


## 1-qism. NumPy ni import qilish

NumPy kutubxonasini `np` qisqartmasi bilan import qiling.


In [3]:
import numpy as np

## 2-qism. Massivlar yaratish

### Topshiriq 1
15 ta nol elementdan iborat NumPy massiv yarating.


In [4]:
# Kodingizni shu yerga yozing
arr = np.zeros(15)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Topshiriq 2
15 ta bir elementdan iborat NumPy massiv yarating.


In [5]:
# Kodingizni shu yerga yozing
arr = np.ones(15)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Topshiriq 3
15 ta yetti sonidan iborat NumPy massiv yarating.


In [6]:
# Kodingizni shu yerga yozing
arr = np.full(15,7)
print(arr)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


### Topshiriq 4
20 dan 60 gacha bo‘lgan butun sonlardan iborat massiv yarating.


In [7]:
# Kodingizni shu yerga yozing
arr = np.arange(20,60)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


### Topshiriq 5
20 dan 60 gacha bo‘lgan faqat juft sonlardan iborat massiv yarating.


In [8]:
# Kodingizni shu yerga yozing
arr = np.arange(20,60,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


### Topshiriq 6
21 dan 59 gacha bo‘lgan faqat toq sonlardan iborat massiv yarating.


In [9]:
# Kodingizni shu yerga yozing
arr = np.arange(21,60,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59]


## 3-qism. Matritsa yaratish

### Topshiriq 7
1 dan 16 gacha bo‘lgan sonlardan iborat 4 x 4 matritsa yarating.


In [10]:
# Kodingizni shu yerga yozing
matrix = np.arange(1,17).reshape(4,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Topshiriq 8
5 x 5 o‘lchamli birlik matritsa yarating.


In [11]:
# Kodingizni shu yerga yozing
matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Topshiriq 9
0 va 1 oralig‘idagi tasodifiy sonlardan iborat 3 x 3 matritsa yarating.


In [12]:
# Kodingizni shu yerga yozing
matrix = np.random.rand(3,3)
print(matrix)

[[0.56336407 0.87926325 0.47113547]
 [0.15201348 0.56536755 0.86117461]
 [0.2082377  0.20439006 0.24274559]]


### Topshiriq 10
Standard normal distribution bo‘yicha 20 ta tasodifiy sonlardan iborat 1D massiv yarating.


In [13]:
# Kodingizni shu yerga yozing
matrix = np.random.rand(20)
print(matrix)

[0.74870953 0.94090514 0.41777588 0.67557696 0.40417388 0.73731333
 0.74912986 0.63749462 0.97659943 0.83646266 0.44543216 0.74159256
 0.59745214 0.05951223 0.62891798 0.04785911 0.71513283 0.10338027
 0.68097133 0.16267935]


### Topshiriq 11
0.01 dan 0.25 gacha bo‘lgan qiymatlardan iborat 5 x 5 matritsa yarating.
Har bir keyingi qiymat 0.01 ga oshib borsin.


In [14]:
# Kodingizni shu yerga yozing
matrix = np.arange(0.01, 0.26, 0.01).reshape(5,5)
print(matrix)

[[0.01 0.02 0.03 0.04 0.05]
 [0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15]
 [0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25]]


### Topshiriq 12
0 dan 5 gacha bo‘lgan 30 ta chiziqli oraliq nuqtadan iborat massiv yarating.


In [15]:
# Kodingizni shu yerga yozing
arr = np.linspace(0,5,30)
print(arr)

[0.         0.17241379 0.34482759 0.51724138 0.68965517 0.86206897
 1.03448276 1.20689655 1.37931034 1.55172414 1.72413793 1.89655172
 2.06896552 2.24137931 2.4137931  2.5862069  2.75862069 2.93103448
 3.10344828 3.27586207 3.44827586 3.62068966 3.79310345 3.96551724
 4.13793103 4.31034483 4.48275862 4.65517241 4.82758621 5.        ]


## 4-qism. Indekslash va slicing

Avval quyidagi kodni ishga tushiring.


In [16]:
import numpy as np

mat = np.arange(1, 37).reshape(6, 6)
mat


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### Topshiriq 13
`mat` dan pastki o‘ng qismidan 3 x 4 o‘lchamli submatritsa ajratib oling.


In [17]:
# Kodingizni shu yerga yozing
mat[3:, 2:]

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

### Topshiriq 14
`mat` dan 21 qiymatini ajratib oling.


In [18]:
# Kodingizni shu yerga yozing
mat[3,2]

np.int64(21)

### Topshiriq 15
`mat` dan quyidagi ustun vektorni ajratib oling:

2
8
14
20


In [19]:
# Kodingizni shu yerga yozing
mat[0:4, 1]

array([ 2,  8, 14, 20])

### Topshiriq 16
`mat` ning oxirgi qatorini ajratib oling.


In [20]:
# Kodingizni shu yerga yozing
mat[5:]

array([[31, 32, 33, 34, 35, 36]])

### Topshiriq 17
`mat` ning oxirgi ikki qatorini ajratib oling.


In [21]:
# Kodingizni shu yerga yozing
mat[4:]

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### Topshiriq 18
`mat` markazidan 3 x 3 o‘lchamli submatritsa ajratib oling.


In [22]:
# Kodingizni shu yerga yozing
mat[2:5,2:5]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

## 5-qism. Hisoblashlar

### Topshiriq 19
`mat` dagi barcha qiymatlar yig‘indisini toping.


In [23]:
# Kodingizni shu yerga yozing
mat.sum()

np.int64(666)

### Topshiriq 20
`mat` dagi barcha qiymatlarning o‘rtacha qiymatini toping.


In [24]:
# Kodingizni shu yerga yozing
mat.mean()

np.float64(18.5)

### Topshiriq 21
`mat` dagi barcha qiymatlarning standart og‘ishini toping.


In [25]:
# Kodingizni shu yerga yozing
mat.std()

np.float64(10.388294694831615)

### Topshiriq 22
`mat` dagi har bir ustun yig‘indisini toping.


In [26]:
# Kodingizni shu yerga yozing
mat.sum(axis=0)

array([ 96, 102, 108, 114, 120, 126])

### Topshiriq 23
`mat` dagi har bir qator yig‘indisini toping.


In [27]:
# Kodingizni shu yerga yozing
mat.sum(axis=1)

array([ 21,  57,  93, 129, 165, 201])

### Topshiriq 24
`mat` dagi har bir ustundagi maksimal qiymatni toping.


In [28]:
# Kodingizni shu yerga yozing
mat.max(axis=0)

array([31, 32, 33, 34, 35, 36])

### Topshiriq 25
`mat` dagi har bir qatordagi minimal qiymatni toping.


In [29]:
# Kodingizni shu yerga yozing
mat.min(axis=1)

array([ 1,  7, 13, 19, 25, 31])

## 6-qism. Boolean indexing

### Topshiriq 26
`mat` dan 20 dan katta bo‘lgan qiymatlarni ajratib oling.


In [ ]:
# Kodingizni shu yerga yozing
mat[mat>20]

### Topshiriq 27
`mat` dan 3 ga karrali bo‘lgan qiymatlarni ajratib oling.


In [ ]:
# Kodingizni shu yerga yozing
mat[mat%3==0]

### Topshiriq 28
`mat` dagi 30 dan katta barcha qiymatlarni -1 ga almashtiring.
Natijani yangi o‘zgaruvchiga saqlang.


In [ ]:
# Kodingizni shu yerga yozing
new_mat = mat.copy()
new_mat[new_mat>30]=-1
print(new_mat)

## 7-qism. Qiziqarliroq topshiriqlar

### Topshiriq 29
0 va 1 lardan iborat 5 x 5 checkerboard matritsa yarating.


In [ ]:
# Kodingizni shu yerga yozing
checkerboard = np.zeros((5, 5), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

### Topshiriq 30
6 x 6 matritsa yarating va chegara elementlarini 1, ichki elementlarini 0 qiling.


In [38]:
# Kodingizni shu yerga yozing
matrix = np.zeros((6, 6), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


### Topshiriq 31
Ikkita 1D massiv yarating va quyidagilarni hisoblang:
- element-wise qo‘shish
- element-wise ko‘paytirish
- dot product


In [35]:
# Kodingizni shu yerga yozing


### Topshiriq 32
Tasodifiy 4 x 4 matritsa yarating va quyidagilarni toping:
- transpose
- determinant
- agar iloji bo‘lsa inverse


In [ ]:
# Kodingizni shu yerga yozing


## 8-qism. Mini challenge

### Topshiriq 33
100 ta talabadan iborat tasodifiy dataset yarating.
Har bir talabaning 3 ta fan bo‘yicha bahosi bo‘lsin:
- Matematika
- Fizika
- Ingliz tili

So‘ng:
- har bir talabaning o‘rtacha bahosini hisoblang
- eng yuqori o‘rtachaga ega talabani toping
- har bir fan bo‘yicha umumiy o‘rtacha bahoni toping


In [37]:
# Kodingizni shu yerga yozing


## Assignment VI yakuni

Ajoyib.
Barcha topshiriqlarni iloji boricha NumPy yordamida bajarishga harakat qiling.
